services:
  postgres_seguro_api:
    image: postgres:latest
    container_name: postgres_seguro_api_db
    env_file:
      - seguro-api/.env/compose.env
    ports:
      - "5434:5432"
    networks:
      - shared_network
    volumes:
      - pgdata_seguro:/var/lib/postgresql/data

  postgres_client_api:
    image: postgres:latest
    container_name: postgres_client_api_db
    env_file:
      -  client-api/.env/compose.env
    ports:
      - "5435:5432"
    networks:
      - shared_network
    volumes:
      - pgdata_agibank:/var/lib/postgresql/data

  client-api:
    build:
      context: ./client-api
      dockerfile: Dockerfile
    container_name: client_app
    ports:
      - "8080:8080"
    env_file:
      - client-api/.env/compose.env
    depends_on:
      - postgres_client_api
    networks:
      - shared_network

  seguro-api:
    build:
      context: ./seguro-api
      dockerfile: Dockerfile
    container_name: seguro_app
    ports:
      - "8081:8081"
    env_file:
      - seguro-api/.env/compose.env
    depends_on:
      - postgres_seguro_api
    networks:
      - shared_network

networks:
  shared_network:

volumes:
  pgdata_agibank:
  pgdata_seguro:
